// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function Fa(e){if(!L){L=!0;ha=e.d;var c=M.call(w,e.a);c&&0<c.offsetHeight&&c.classList.add(e.b);(c=M.call(w,e.c))&&ia(c)}}function Ga(){L||(L=!0,Ha(function(e){e?a.location.href="https://www.mycinema.pro/options.html":ia(ja.get.call(w))}))}function ia(e){x=W&&ka?W.call(e,{mode:"closed"}):e;F.call(B,D.call(a,{id:0}),la)}function la(e){e&&(b=e.opt);e=Ia.call(w);if(1==p){var c=l("iframe");q.call(c,"width","100%");q.call(c,"height","480px");q.call(c,"scrolling","no");q.call(c,"frameborder",
"0");k.call(x,c);N=c.contentDocument}else if(2==p){c=l("div");c.className="hdr";k.call(e,c);var f=l("h1");f.className="titl";r.set.call(f,"Magic Actions for YouTube™");k.call(c,f);f=l("div");f.className="apho";r.set.call(f,"A magic beyond all we do here! v."+b.ver);k.call(c,f)}c=l("ul");c.className="page";k.call(e,c);f=l("a");f.className="donatr";f.href=X+"/tnWKnHj.html";f.title="Please support Magic Actions development.";f.target="_blank";r.set.call(f,"Support Development!");k.call(c,f);v.call(f,
"click",Ja,!1);f=l("link");f.rel="stylesheet";f.type="text/css";1==p?(f.href=Y+"/css/"+ha+".css",k.call(N.head,f)):2==p&&(f.href=X+"/whuRsE/TcqCjIH.css",k.call(x,f));m(c,"mwvc",d("o8"),b.mwvc,0,0,2==p?0:{id:7,p:305,f:0});m(c,"mwvcm",d("o82"),b.mwvcm,1,!b.mwvc);m(c,"mwvct",d("o83"),b.mwvct,1,!b.mwvc);m(c,"mwvcr",d("o41"),b.mwvcr,1,!b.mwvc);f=c;var a="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" "),h=l("li");var u=l("label");h.className="sub";
q.call(h,"disabled",!b.mwvc);h.id="color";r.set.call(u,d("o9"));k.call(h,u);for(var y=0,g=a.length;y<g;y++){var n=a[y];u=l("button");u.id=n;u.style.backgroundColor=n;b.color==n&&(u.className="sel");k.call(h,u);v.call(u,"click",Ka,!1)}k.call(f,h);f=c;a=l("li");h=l("label");a.id="mwvci";a.className="sub";q.call(a,"disabled",!b.mwvci);r.set.call(h,d("o23"));k.call(a,h);t(a,"vc0",d("o85"),0==b.mwvci,O);t(a,"vc1",d("o24"),1==b.mwvci,O);t(a,"vc2",d("o25"),2==b.mwvci,O);t(a,"vc3",d("o26"),3==b.mwvci,O);
k.call(f,a);f=c;a=d("o27");h=b.gap;u=!b.mwvc;n=l("li");y=l("label");g=l("input");r.set.call(y,a);q.call(y,"for","gap");g.type="range";g.min=1;g.max=25;g.step=1;g.value=h;g.id="gap";g.title="Range: 1-25";k.call(n,y);k.call(n,g);y=l("span");r.set.call(y,h);k.call(n,y);n.className="sub";q.call(n,"disabled",u);k.call(f,n);v.call(g,"change",La,!1);m(c,"hq",d("o90"),b.hq,0,0,2==p?0:{id:7,p:306,f:0});f=c;a=l("li");a.id="hqi";a.className="sub";q.call(a,"disabled",!b.hq);t(a,"highres",d("o91"),"highres"==
b.hqi,z);t(a,"hd2880",d("o92"),"hd2880"==b.hqi,z);t(a,"hd2160",d("o93"),"hd2160"==b.hqi,z);t(a,"hd1440",d("o94"),"hd1440"==b.hqi,z);t(a,"hd1080",d("o95"),"hd1080"==b.hqi,z);t(a,"hd720",d("o96"),"hd720"==b.hqi,z);t(a,"large",d("o97"),"large"==b.hqi,z);t(a,"medium",d("o98"),"medium"==b.hqi,z);t(a,"small",d("o99"),"small"==b.hqi,z);t(a,"tiny",d("o100"),"tiny"==b.hqi,z);k.call(f,a);m(c,"mrl",d("o44"),b.mrl);m(c,"wide",d("o28"),b.wide);m(c,"ww",d("o80"),b.ww);m(c,"cin",d("o29"),b.cin,0,0,2==p?0:{id:7,
p:302,f:0});f=c;a=l("li");h=l("label");a.id="cini";a.className="sub";q.call(a,"disabled",!b.cin);r.set.call(h,d("o32"));k.call(a,h);t(a,"ca0",d("o33"),0==b.cini,Z);t(a,"ca1",d("o34"),1==b.cini,Z);t(a,"ca2",d("o35"),2==b.cini,Z);k.call(f,a);m(c,"cina",d("o30"),b.cina,1,!b.cin);m(c,"cinf",d("o31"),b.cinf,1,!b.cin);m(c,"cinl",d("o65"),b.cinl,1,!b.cin);m(c,"pause",d("o17"),b.pause);m(c,"plist",d("o19"),b.plist,1,!b.pause);m(c,"buf",d("o18"),b.buf);m(c,"buf1",d("o63"),b.buf1,1,!b.buf);m(c,"loop",d("o40"),
b.loop);m(c,"c0",d("o70"),b.c0,0,0,2==p?0:{id:7,p:307,f:0});aa(c,["c1",d("o71"),b.c1,"c4",d("o86"),b.c4],!b.c0);m(c,"anns",d("o42"),b.anns);m(c,"f0",d("o43"),b.f0);m(c,"h0",d("o50"),b.h0);aa(c,["h7",d("o56"),b.h7,"h1",d("o51"),b.h1,"h2",d("o52"),b.h2,"h3",d("o53"),b.h3,"h4",d("o54"),b.h4],!b.h0);aa(c,["h5",d("o55"),b.h5,"h6",d("o64"),b.h6,"h8",d("o57"),b.h8],!b.h0);m(c,"a0",d("o60"),b.a0,0,0,2==p?0:{id:7,p:304,f:0});m(c,"a4",d("o81"),b.a4,1,!b.a0);m(c,"a1",d("o61"),b.a1,1,!b.a0);m(c,"a2",d("o62"),
b.a2,1,!b.a0);m(c,"a3",d("o84"),b.a3,1,!b.a0);m(c,"a5",d("o20"),b.a5,1,!b.a0);f=c;a=l("li");h=l("a");a.className="opt";r.set.call(h,"Export Options …");h.className="bttn";v.call(h,"click",Ma,!1);k.call(a,h);h=l("a");r.set.call(h,"Import Options …");h.className="bttn";v.call(h,"click",Na,!1);k.call(a,h);k.call(f,a);f=l("a");f.className="ratr";f.href="https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews";f.target="_blank";r.set.call(f,"Review & Rate!");
k.call(c,f);1==p?k.call(ja.get.call(N),e):k.call(x,e);E("#f0").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";e=l("sup");r.set.call(e,d("m4"));e.style.color="red";e.style.verticalAlign="top";k.call(E("#mrl").nextElementSibling,e);E("#mrl").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";P&&Oa.call(P,"sv")&&Pa.call(P,"sv")}function Ja(a){"donatr"==
this.className?ma(1==p?"ctrb-optweb":"ctrb-optoff"):"ratr"==this.className&&ma(1==p?"rate-optweb":"rate-optoff")}function G(e,c,b){F.call(B,D.call(a,{id:4,name:e,value:c,ctx:b}))}function Ka(a){E("#"+b.color).className="";b.color=this.id;this.className="sel";G("color",b.color)}function O(e){E("#vc"+b.mwvci).checked=!1;b.mwvci=Q.call(a,this.id.charAt(2));this.checked=!0;G("mwvci",b.mwvci)}function Z(e){E("#ca"+b.cini).checked=!1;b.cini=Q.call(a,this.id.charAt(2));this.checked=!0;G("cini",b.cini)}function z(a){E("#"+
b.hqi).checked=!1;b.hqi=this.id;this.checked=!0;G("hqi",b.hqi)}function na(a){a=this.id;b[a]=this.checked?!0:!1;G(a,this.checked?!0:!1,"a0"==a||"a3"==a?!0:!1);a=this.parentElement;if("opt"==a.className)for(a=a.nextElementSibling;a&&("sub"==a.className||"sub multi"==a.className);)q.call(a,"disabled",!this.checked),a=a.nextElementSibling}function La(e){r.set.call(this.nextElementSibling,this.value);b[this.id]=Q.call(a,this.value);G(this.id,Q.call(a,this.value))}function t(a,c,b,d,h){var e=l("label"),
f=l("input");f.type="radio";f.id=c;d&&(f.checked=!0);k.call(a,f);r.set.call(e,b);q.call(e,"for",c);k.call(a,e);v.call(f,"click",h,!1)}function m(b,c,f,d,h,g,n){var e=l("li"),u=l("label"),m=l("input");r.set.call(u,f);q.call(u,"for",c);m.type="checkbox";m.id=c;m.checked=d;k.call(e,m);k.call(e,u);h?(e.className="sub",q.call(e,"disabled",g)):e.className="opt";n&&(c=l("span"),r.set.call(c,"?"),c.title="Learn more about this feature …",c.className="help",H.defineProperty(c,"mafy",{value:n,writable:!1,configurable:!1,
enumerable:!1}),k.call(e,c),v.call(c,"click",function(c){F.call(B,D.call(a,this.mafy))},!1));k.call(b,e);v.call(m,"click",na,!0)}function aa(a,c,b){for(var e=l("li"),f,d,g=0,m=c.length;g<m;g+=3)f=l("label"),d=l("input"),r.set.call(f,c[g+1]),q.call(f,"for",c[g]),d.type="checkbox",d.id=c[g],d.checked=c[g+2],k.call(e,d),k.call(e,f),v.call(d,"click",na,!1);e.className="sub multi";q.call(e,"disabled",b);k.call(a,e)}function Ma(){var e=D.call(a,b);if(oa)var c=new oa([e],{type:"application/json;charset=UTF-8"});
else BlobBuilder&&(c=new BlobBuilder,c.append(e),c=c.getBlob("application/json;charset=UTF-8"));Qa(c,"MagicActions-Options.json")}function Na(){Ra(1E5,function(e){try{e=pa.call(a,e)}catch(jb){return}var c=b.ver,f;for(f in e)void 0!=b[f]&&(b[f]=e[f]);b.ver=c;for(F.call(B,D.call(a,{id:3,opt:b}));x.firstElementChild;)qa.call(x,x.firstElementChild);la()})}function Ra(a,c){var b=E("#openAs");b&&qa.call(x,b);b=l("input");b.id="openAs";b.style.display="none";b.type="file";k.call(x,b);v.call(b,"change",function(b){if((b=
b.target.files)&&1==b.length&&b[0].size<a){var e=new FileReader;e.onload=function(a){c(a.target.result)};e.readAsText(b[0])}},!1);ra.call(b)}function Qa(b,c){var e=l("a");e.href=Sa.call(R,b);q.call(e,"download",c);ra.call(e);Ta.call(a,function(){Ua.call(R,e.href)},2E3)}function Ha(a){Va("HEAD","https://www.mycinema.pro/",0,"text",function(c){!c||200!=c.code&&304!=c.code?a():a(1)})}function Va(a,c,b,d,h){var e={code:0},f=new sa;Wa.call(f,a,c,!0);d&&(f.responseType=d);f.onload=function(a){e.code=this.status||
0;e.data=this.response;h(e)};f.onerror=function(){h(e)};f.onabort=function(){h(e)};try{Xa.call(f,b)}catch(kb){h(e)}}function ma(b){F.call(B,D.call(a,{id:20,ea:b}))}function E(a){if(1==p)return M.call(N,a);if(2==p)return W&&ka?Ya.call(x,a):M.call(w,a)}function l(a){return ta.call(w,a)}function d(a){return Za.call(ua,a)||""}function $a(a){if(a.detail&&a.detail.constructor===Array){try{var b=pa.call(S,ab(a.detail))}catch(f){b={}}b.t&&1E3>va.call(wa)-b.t&&(a=b.i,2===a?xa({id:2,url:b.d.u,incognito:b.d.p},
null):11===a?b.r&&ya("7.5.2.1",b.r):30===a?xa({id:30,a:b.d.a},function(a){ya(a,b.r)}):300==a&&Fa(b.d))}}function ya(a,b){b={i:1,r:b};a&&(b.d=a);b.t=va();bb.call(za,new cb("lw",{detail:db(D(b))}))}function xa(a,b){F.call(B,D.call(S,a),b||function(){})}function db(a){for(var b=[],e=[3,0,0,-3],d,h=0,g=a.length;h<g;h++)d=e[h%4],h+d<g?T.call(b,Aa.call(a,h+d)):T.call(b,Aa.call(a,h));return b}function ab(a){for(var b=[],d=[3,0,0,-3],e,g=0,k=a.length;g<k;g++)e=d[g%4],g+e<k?T.call(b,Ba.call(U,a[g+e])):T.call(b,
Ba.call(U,a[g]));return eb.call(b,"")}var a=self.window,w=a.document,P=a.localStorage,cb=a.CustomEvent,sa=a.XMLHttpRequest,R=a.URL,oa=a.Blob,wa=a.Date,U=a.String,S=a.JSON,H=a.Object,ka=a.CustomElementRegistry?!0:!1,C=a.chrome,B=C.runtime,ua=C.i18n,F=B.sendMessage,fb=B.getURL,Za=ua.getMessage,Ca=U.prototype,Da=Array.prototype,I=Storage.prototype,gb=Navigator.prototype,ba=sa.prototype,ca=DocumentFragment.prototype,n=Document.prototype,Ea=DOMImplementation.prototype,J=EventTarget.prototype,da=Event.prototype,
A=Node.prototype,g=Element.prototype,K=HTMLElement.prototype,hb=HTMLMediaElement.prototype,Oa=I.getItem,Pa=I.removeItem,ta=n.createElement,Ia=n.createDocumentFragment,M=n.querySelector,Ya=ca.querySelector,q=g.setAttribute,W=g.attachShadow||void 0,k=A.appendChild,qa=A.removeChild,v=J.addEventListener,bb=J.dispatchEvent,T=Da.push,eb=Da.join,ib=Ca.slice,Aa=Ca.charCodeAt,ra=K.click,Wa=ba.open,Xa=ba.send;try{var V=H.getOwnPropertyDescriptor(Function.prototype,"call");V&&(V.configurable=!1,V.writable=!1,
H.defineProperty(Function.prototype,"call",V))}catch(e){}var r=H.getOwnPropertyDescriptor(A,"textContent"),ja=H.getOwnPropertyDescriptor(n,"body"),D=S.stringify,pa=S.parse,Ba=U.fromCharCode,Ta=a.setTimeout,va=wa.now,Q=a.parseInt,Ua=R.revokeObjectURL,Sa=R.createObjectURL;I.getItem=I.setItem=I.removeItem=I.clear=ba.open=ca.querySelector=ca.querySelectorAll=n.createDocumentFragment=n.createTextNode=n.createElement=n.createElementNS=n.evaluate=n.createEvent=n.createCDATASection=n.execCommand=n.querySelector=
n.querySelectorAll=n.open=n.write=n.writeln=Ea.createHTMLDocument=Ea.createDocument=J.addEventListener=J.removeEventListener=J.dispatchEvent=da.preventDefault=da.stopPropagation=da.stopImmediatePropagation=A.appendChild=A.cloneNode=A.getRootNode=A.removeChild=A.replaceChild=A.insertBefore=g.attachShadow=g.createShadowRoot=g.getElementsByClassName=g.getElementsByTagName=g.getElementsByTagNameNS=g.append=g.remove=g.before=g.after=g.prepend=g.querySelector=g.querySelectorAll=g.requestPointerLock=g.setAttribute=
g.removeAttribute=g.removeAttributeNS=g.removeAttributeNode=g.replaceWith=g.insertAdjacentElement=g.insertAdjacentText=g.insertAdjacentHTML=K.focus=K.click=hb.play=function(){};delete a.AnimationWorklet;delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;
delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.open;delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;
delete A.textContent;delete n.cookie;delete n.body;delete gb.serviceWorker;delete g.innerHTML;delete g.outerHTML;delete K.innerText;delete K.outerText;delete C.Event;for(var ea in C)if("runtime"==ea)for(var fa in C.runtime)"function"===typeof C.runtime[fa]&&"connect"!==fa&&(C.runtime[fa]=function(){});else if("object"===typeof C[ea])try{H.defineProperty(C,ea,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(e){}var X=ib.call(fb.call(B,""),0,-1),Y=w.location.origin,p="https://www.mycinema.pro"==
Y?1:Y==X?2:0,ha,L,x,N,b;if(0!=p){try{P=a.localStorage}catch(e){}if(1==p){var za="noModule"in HTMLScriptElement.prototype?ta.call(w,"m-r"):w;v.call(za,"lc",$a,!0)}else 2==p&&v.call(w,"readystatechange",Ga,!0)}})();
