// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function F(){function a(b,c){for(var h,u,d=0,f=c.length;d<f;d++)if(node=c[d],1==node.t){h=G.call(k,node.l);for(var e=0,g=node.a&&node.a.length||0;e<g;e++)u=node.a[e],H.call(h,u.n,u.v);node.c&&a(h,node.c);t.call(b,h)}else 3==node.t&&t.call(b,I.call(k,node.v))}var b=J.call(m,'[{"t":1,"l":"link","a":[{"n":"rel","v":"stylesheet"},{"n":"type","v":"text/css"},{"n":"href","v":"whuRsE/nXNj.css"}]},{"t":1,"l":"div","a":[{"n":"class","v":"host"}],"c":[{"t":1,"l":"h1","c":[{"t":3,"v":"Thank You for using Magic Actions"}]},{"t":1,"l":"h3","c":[{"t":3,"v":"Software Made to Make Your Life Better!"}]},{"t":1,"l":"button","a":[{"n":"class","v":"b0"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"Fjtq/home64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Home"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b1"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"Fjtq/opt64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Options"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b2"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"Fjtq/rate64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Rate"}]}]},{"t":1,"l":"button","a":[{"n":"class","v":"b3"}],"c":[{"t":1,"l":"img","a":[{"n":"src","v":"Fjtq/contact64.png"}]},{"t":1,"l":"b","c":[{"t":3,"v":"Support"}]}]},{"t":1,"l":"br"}]}]');
n=v&&A?v.call(B.get.call(k),{mode:"closed"}):B.get.call(k);var c=K.call(k);a(c,b);t.call(n,c)}function L(){M.call(N(".b0"));C.call(n,"click",function(a){var b=a.target;if(b=b.className||b.parentElement&&b.parentElement.className||""){if("b0"===b){var c=99;var d=104}else"b1"===b?(c=300,d=200):"b2"===b?(c=101,d=0):"b3"===b&&(c=303,d=104);O.call(p,P.call(m,{id:7,p:c,f:d}));Q.call(a);R.call(a)}},!0)}function N(a){return v&&A?S.call(n,a):T.call(k,a)}var a=self.window,k=a.document,m=a.JSON,e=a.Object,A=
a.CustomElementRegistry?!0:!1,d=a.chrome,p=d.runtime,O=p.sendMessage,U=p.getURL,q=Storage.prototype,D=Navigator.prototype,V=XMLHttpRequest.prototype,w=DocumentFragment.prototype,c=Document.prototype,E=DOMImplementation.prototype,x=EventTarget.prototype,g=Event.prototype,f=Node.prototype,b=Element.prototype,l=HTMLElement.prototype,G=c.createElement,C=x.addEventListener,K=c.createDocumentFragment,H=b.setAttribute,S=w.querySelector,T=c.querySelector,M=l.focus,t=f.appendChild,I=c.createTextNode,Q=g.preventDefault,
R=g.stopPropagation,W=a.String.prototype.indexOf,v=b.attachShadow||void 0;try{var r=e.getOwnPropertyDescriptor(Function.prototype,"call");r&&(r.configurable=!1,r.writable=!1,e.defineProperty(Function.prototype,"call",r))}catch(h){}var B=e.getOwnPropertyDescriptor(c,"body"),P=m.stringify,J=m.parse;q.getItem=q.setItem=q.removeItem=q.clear=D.sendBeacon=V.open=w.querySelector=w.querySelectorAll=c.createDocumentFragment=c.createTextNode=c.createElement=c.createElementNS=c.evaluate=c.createEvent=c.createCDATASection=
c.execCommand=c.querySelector=c.querySelectorAll=c.open=c.write=c.writeln=E.createHTMLDocument=E.createDocument=x.addEventListener=x.removeEventListener=g.preventDefault=g.stopPropagation=g.stopImmediatePropagation=f.appendChild=f.cloneNode=f.getRootNode=f.removeChild=f.replaceChild=f.insertBefore=b.attachShadow=b.createShadowRoot=b.getElementsByClassName=b.getElementsByTagName=b.getElementsByTagNameNS=b.append=b.remove=b.before=b.after=b.prepend=b.querySelector=b.querySelectorAll=b.requestPointerLock=
b.setAttribute=b.removeAttribute=b.removeAttributeNS=b.removeAttributeNode=b.replaceWith=b.insertAdjacentElement=b.insertAdjacentText=b.insertAdjacentHTML=l.focus=l.click=function(){};delete a.AnimationWorklet;delete a.AudioContext;delete a.Blob;delete a.CSS;delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;
delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.open;delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;
delete f.textContent;delete c.cookie;delete c.body;delete D.serviceWorker;delete b.innerHTML;delete b.outerHTML;delete l.innerText;delete l.outerText;delete d.Event;for(var y in d)if("runtime"==y)for(var z in d.runtime)"function"===typeof d.runtime[z]&&"connect"!==z&&(d.runtime[z]=function(){});else if("object"===typeof d[y])try{e.defineProperty(d,y,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(h){}e=U.call(p,"qHIVS.html");var n;0!==W.call(a.location.href,e)&&(a.location.href=
e);C.call(a,"DOMContentLoaded",function(){F();L()},!0)})();
