#!/bin/bash

battery_warning() {
    ttl='BATTERY WARNING'
    msg='BATTERY AT 5%! PLUG IN YOUR DAMN CHARGER'
    notify-send "$ttl" "$msg" -u critical
}

NUM=`cat /sys/class/power_supply/BAT0/capacity` || exit
STATUS=`cat /sys/class/power_supply/BAT0/status`

if [ "$NUM" -ge 80 ]; then
    color="#00FF00"
elif [ "$NUM" -ge 60 ]; then
    color="#FFFFFF"
elif [ "$NUM" -ge 40 ]; then
    color="#FFF600"
elif [ "$NUM" -ge 20 ]; then
    color="#FFAE00"
elif [ "$NUM" -eq 5 ]; then
    if [ "$STATUS" = "Charging" ]; then
        color="#FF0000"
    else
        battery_warning
        color="#FF0000"
    fi
else
    color="#FF0000"
fi

[ "$STATUS" = "Charging" ] && color="#FFF"

echo "<span color='$color'>`sed -e "s/,//g;s/Discharging/🔋/;s/Charging/🔌/;s/Unknown/❓/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g" <<<"$STATUS"` `sed -e 's/$/%/' <<<"$NUM"`</span>"

