#!/bin/bash

battery_warning() {
        ttl='BATTERY WARNING'
        msg='BATTERY AT 5%! PLUG IN YOUR DAMN CHARGER'
        notify-send "$ttl" "$msg" -u critical
}

NUM=`cat /sys/class/power_supply/BAT0/capacity` || exit
STATUS=`cat /sys/class/power_supply/BAT0/status`

if [ "$NUM" -ge 80 ]; then
        color="#ffffff"
elif [ "$NUM" -ge 60 ]; then
        color="#ebddb2"
elif [ "$NUM" -ge 40 ]; then
        color="#fff600"
elif [ "$NUM" -ge 20 ]; then
        color="#ffae00"
elif [ "$NUM" -eq 5 ]; then
        battery_warning
        color="#ff0000"
else
        color="#ff0000"
fi

[ "$STATUS" = "Charging" ] && color="#3df637"

echo "<span color='$color'>`sed -e "s/,//g;s/Discharging/🔋/;s/Charging/🔌/;s/Unknown/❓/;s/Full/⚡/;s/ 0*/ /g;s/ :/ /g" <<<"$STATUS"` `sed -e 's/$/%/' <<<"$NUM"`</span>"

