// MagicActions for Google Chrome - CHROMEACTIONS.COM - Copyright (c) 2018 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function A(a,b){b={i:1,r:b};a&&(b.d=a);b.t=B.call(r);P.call(C,new Q("lw",{detail:R(D.call(h,b))}))}function t(a,b){S.call(u,D.call(h,a),b||function(){})}function E(e){var b=e?e:{w:640,h:350,vid:"pwHX9JT2APQ",lic:"YouTube License",t:"Magic Actions for YouTube™"};b.ver="7.5.2.1";b.ua=1;b.id=12;e=new F;T.call(e,"GET",b.rgba,!0);e.responseType="arraybuffer";e.onload=function(e){200==this.status&&(b.rgba=this.response,U.call(a,b,"https://www.mycinema.pro"))};V.call(e)}function R(a){for(var b=
[],e=[3,0,0,-3],c,d=0,f=a.length;d<f;d++)c=e[d%4],d+c<f?l.call(b,G.call(a,d+c)):l.call(b,G.call(a,d));return b}function W(a){for(var b=[],c=[3,0,0,-3],d,e=0,f=a.length;e<f;e++)d=c[e%4],e+d<f?l.call(b,H.call(m,a[e+d])):l.call(b,H.call(m,a[e]));return X.call(b,"")}var a=self.window,I=a.document,Q=a.CustomEvent,F=a.XMLHttpRequest,r=a.Date,m=a.String,h=a.JSON,v=a.Object,f=a.chrome,u=f.runtime,J=u.onMessage,S=u.sendMessage,Y=J.addListener,K=Array.prototype,n=Storage.prototype,L=Navigator.prototype,w=F.prototype,
M=DocumentFragment.prototype,d=Document.prototype,N=DOMImplementation.prototype,k=EventTarget.prototype,x=Event.prototype,g=Node.prototype,c=Element.prototype,p=HTMLElement.prototype,Z=d.createElement,aa=k.addEventListener,P=k.dispatchEvent,T=w.open,V=w.send,l=K.push,X=K.join,G=m.prototype.charCodeAt,D=h.stringify,ba=h.parse,H=m.fromCharCode,B=r.now,U=a.postMessage;try{var q=v.getOwnPropertyDescriptor(Function.prototype,"call");q&&(q.configurable=!1,q.writable=!1,v.defineProperty(Function.prototype,
"call",q))}catch(e){}n.getItem=n.setItem=n.removeItem=n.clear=L.sendBeacon=w.open=M.querySelector=M.querySelectorAll=d.createDocumentFragment=d.createTextNode=d.createElement=d.createElementNS=d.evaluate=d.createEvent=d.createCDATASection=d.execCommand=d.querySelector=d.querySelectorAll=d.open=d.write=d.writeln=N.createHTMLDocument=N.createDocument=k.addEventListener=k.removeEventListener=k.dispatchEvent=x.preventDefault=x.stopPropagation=x.stopImmediatePropagation=g.appendChild=g.cloneNode=g.getRootNode=
g.removeChild=g.replaceChild=g.insertBefore=c.attachShadow=c.createShadowRoot=c.getElementsByClassName=c.getElementsByTagName=c.getElementsByTagNameNS=c.append=c.remove=c.before=c.after=c.prepend=c.querySelector=c.querySelectorAll=c.requestPointerLock=c.setAttribute=c.removeAttribute=c.removeAttributeNS=c.removeAttributeNode=c.replaceWith=c.insertAdjacentElement=c.insertAdjacentText=c.insertAdjacentHTML=p.focus=p.click=function(){};delete a.AnimationWorklet;delete a.AudioContext;delete a.Blob;delete a.CSS;
delete a.CustomElementRegistry;delete a.CustomEvent;delete a.DOMImplementation;delete a.DOMParser;delete a.Event;delete a.FormData;delete a.Image;delete a.JSON;delete a.LayoutWorklet;delete a.MutationObserver;delete a.Navigator;delete a.PaintWorklet;delete a.Proxy;delete a.Range;delete a.Request;delete a.Response;delete a.ServiceWorker;delete a.SharedWorker;delete a.Storage;delete a.URL;delete a.WebAssembly;delete a.WebSocket;delete a.Worker;delete a.XMLHttpRequest;delete a.XMLHttpRequestUpload;delete a.XMLSerializer;
delete a.XSLTProcessor;delete a.fetch;delete a.close;delete a.open;delete a.alert;delete a.confirm;delete a.eval;delete a.localStorage;delete a.postMessage;delete a.prompt;delete a.stop;delete a.customElements;delete a.navigator;delete g.textContent;delete d.cookie;delete d.body;delete L.serviceWorker;delete c.innerHTML;delete c.outerHTML;delete p.innerText;delete p.outerText;delete f.Event;for(var y in f)if("runtime"==y)for(var z in f.runtime)"function"===typeof f.runtime[z]&&"connect"!==z&&(f.runtime[z]=
function(){});else if("object"===typeof f[y])try{v.defineProperty(f,y,{configurable:!1,enumerable:!1,writable:!1,value:{}})}catch(e){}var O;var C="noModule"in HTMLScriptElement.prototype?Z.call(I,"m-r"):I;aa.call(C,"lc",function(a){if(a.detail&&a.detail.constructor===Array){try{var b=ba.call(h,W(a.detail))}catch(ca){b={}}b.t&&1E3>B.call(r)-b.t&&(a=b.i,2===a?t({id:2,url:b.d.u,incognito:b.d.p},null):11===a?b.r&&A("7.5.2.1",b.r):30===a?t({id:30,a:b.d.a},function(a){A(a,b.r)}):303==a&&(O||(O=!0,Y.call(J,
E),t({id:9},E))))}},!0)})();
