#! /bin/sh
#                       ####  #    # #    # #    # #####
#                      #       #  #  #    # #   #  #    #
#                       ####    ##   ###### ####   #    #
#                           #   ##   #    # #  #   #    #
#                      #    #  #  #  #    # #   #  #    #
#                       ####  #    # #    # #    # #####
#
########################## SXHKD Configuration File ###########################


###############################################################################
########################### Window Manager Control ############################
###############################################################################
# sxhkdrc [reload | quit/restart | close/kill]
super + c
    pkill -USR1 -x sxhkd

super + shift + {x,c}
    bspc {quit,wm -r}

super + {_,shift + }q
    bspc node -{c,k}

# power control [suspend | shutdown prompt]
super + shift + p
    lockScreen & systemctl suspend

alt + Delete
    ~/.config/polybar/scripts/i3shutdown

############################### Volume Control ################################
XF86AudioMute
    pulseaudio-ctl mute

XF86AudioRaiseVolume
    pulseaudio-ctl up 05

shift + XF86AudioRaiseVolume
    pulseaudio-ctl up 10

ctrl + XF86AudioRaiseVolume
    pulseaudio-ctl up 01

XF86AudioLowerVolume
    pulseaudio-ctl down 05

shift + XF86AudioLowerVolume
    pulseaudio-ctl down 10

ctrl + XF86AudioLowerVolume
    pulseaudio-ctl down 01

############################# Brightness Control ##############################
XF86MonBrightnessDown
    xbacklight -dec 5

shift + XF86MonBrightnessDown
    xbacklight -dec 10

ctrl + XF86MonBrightnessDown
    xbacklight -dec 1

XF86MonBrightnessUp
    xbacklight -inc 5

shift + XF86MonBrightnessUp
    xbacklight -inc 10

ctrl + XF86MonBrightnessUp
    xbacklight -inc 1

ctrl + shift + XF86MonBrightnessDown
    xbacklight -set 1

ctrl + shift + XF86MonBrightnessUp
    xbacklight -set 100

############################### Display Control ###############################
# Display control [xrandr]
alt + z
    setScreens 1

alt + shift + z
    setScreens 2

ctrl + shift + z
    setScreens 3

###############################################################################
################################ Applications #################################
###############################################################################

############################### Main Utilities ################################
# Terminals [urxvtc , tmux , kitty]
super + Return
    urxvt

super + shift + Return
    kitty

super + grave
    urxvtc

alt + grave
    urxvtc -e tmux

alt + shift + grave
    urxvtc -name float

super + n
    urxvtc

super + shift + n
    urxvtd -q -o -f

super + b
    kitty -e tmux

# Program launcher
super + d
    rofi_run

ctrl + alt + d
    switchRofi

# System Utilities [ranger , htop , gotop ]
super + r
    urxvt -e ranger

super + alt + r
    romoji

super + alt + p
    clippw lp clip 1

super + ctrl + p
    clippw pw clip 1

alt + ctrl + p
    clippw gm clip 1

ctrl + shift + p
    clippw pg clip 1

super + ctrl + h
    urxvt -name htop -e htop

alt + ctrl + h
    urxvt -name gotop -e gotop -p -b -s -r 2

alt + shift + h
    urxvt -name nvtop -e nvtop

############################### Misc Utilities ################################
# Browsers [brave , firefox , qutebrowser , surf]
super + shift + f
    firefox

super + shift + g
    brave

alt + shift + g
    google-chrome-beta

ctrl + shift + g
    droidsurf chrome labmeeting

super + shift + h
    qutebrowser

ctrl + shift + h
    surf google.com

## Misc applications [touchpad, mpd, screenshot, screenrecord, vimwiki]
# Touchpad
alt + t
    touchpadctl dev 1

ctrl + alt + t
    touchpadctl tap 1

# MPD
XF86AudioPrev
    mpc prev

XF86AudioPlay
    mpc toggle

XF86AudioNext
    mpc next

ctrl + alt + x
    showSongInfo 1

# VimWiki
alt + o
    urxvt -e nvim -c :VimwikiDiaryIndex

alt + p
    urxvt -e nvim -c :VimwikiMakeDiaryNote

# Screenshot / Screen recording
Print
    scrt 0

shift + Print
    scrt 0 a

super + Print
    simplescreenrecorder


alt + w
    weather

# Function applications [Fn Keys]
super + XF86AudioMute
    nvidia-settings

super + XF86AudioLowerVolume
    gpmdp

super + XF86AudioRaiseVolume
    spotify

super + XF86AudioPrev
    droidsurf brave fbmessenger

super + XF86AudioPlay
    droidsurf brave droid

super + XF86AudioNext
    droidsurf brave ghangouts

super + F7
    droidsurf brave reddit

super + XF86Display
    droidsurf brave twitter

super + XF86Search
    krita

# Must hold Fn key [can't override keyboard brightness]
super + F10
    inkscape

super + XF86MonBrightnessDown
    gimp

super + XF86MonBrightnessUp
    fiji

# Alternative Function applications [Alt + Fn Keys]
alt + XF86AudioMute
    droidsurf chrome labmeeting

alt + XF86AudioLowerVolume
    urxvt -name ncmpcpp -e ncmpcpp

#alt + XF86AudioRaiseVolume
alt + F3
    arandr

#alt + XF86AudioPrev
alt + F4
    urxvt -name pulsemixer -e pulsemixer

alt + XF86AudioPlay
    urxvt -e openmutt gmail

alt + XF86AudioNext
    urxvt -e openmutt wisc

alt + F7
    urxvt -e openmutt pmail

# Must hold Fn key [can't override odd paste function]
alt + F8
    steam

alt + XF86Search
    urxvt -name conkyconf -e nvim ~/Dropbox/Misc/config/conky/notepad/todo.md

# Must hold Fn key [can't override keyboard brightness]
alt + F10
    urxvt -name conkyconf -e nvim ~/Dropbox/Misc/config/conky/notepad/shopping.md

#alt + XF86MonBrightnessDown
alt + F11
    themeSwitch day 0

#alt + XF86MonBrightnessUp
alt + F12
    themeSwitch night 0

###############################################################################
############################# General Navigation ##############################
###############################################################################

############################## Navigate Focus #################################
# Focus node in given direction
super + {_,shift + }{j,k,l,semicolon}
    bspc node -{f,s} {west,south,north,east}

# Focus node for given path jump
super + {p,b,comma,period}
    bspc node -f @{parent,brother,first,second}

# Focus next/previous node in current desktop
alt + {_,shift + }c
    bspc node -f {next,prev}.local

# Focus next/previous desktop in current monitor
super + bracket{left,right}
    bspc desktop -f {prev,next}.local

super + shift + bracket{left,right}
    bspc node -d {prev,next}.local

# Focus last node/desktop
super + Tab
    bspc desktop -f last

# Focus older or newer node in focus history
super + {o,i}
    bspc wm -h off; \
    bspc node {older,newer} -f; \
    bspc wm -h on

########################### Move Between Workspaces ###########################
# Focus or send to given desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

# Use alt + 1-5 to send to secondary display
ctrl + {_,shift + }{1,2,3,4,5}
    bspc {desktop -f,node -d} '^{6,7,8,9,10}'

# Use alt + 6-9,0 to send to tertiary display
#ctrl + {_,shift + }{1,2,3,4,5}
    #bspc {desktop -f,node -d} '^{11,12,13,14,15}'

# Toggle window from scratchpad
super + {shift +}minus
    id=$(cat /tmp/scratchid); \
        bspc node $id --flag hidden;bspc node -f $id

super + minus
    id=$(cat /tmp/scratchid); \
        bspc node $id --flag marked=on;bspc node -f $id

# Move focus to next desktop
super + {_,shift + }w
        bspc {monitor -f next,node -m next}

#super + w
#        bspc monitor -f next

# Preselect the direction/ratio
super + ctrl + {j,k,l,semicolon}
    bspc node -p {west,south,north,east}

#super + ctrl + {1-9}
super + alt + {1-9}
    bspc node -o 0.{1-9}

# Set split orientation [h: horizontal (east) | v: vertical (south)]
super + {h,v}
    bspc node -p {east,south}

# Cancel the preselection for the focused node/desktop
super + ctrl + space
    bspc node -p cancel

super + ctrl + shift + space
    bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

############################### Resize Windows ################################
# Expand window by moving one side outward
super + shift + {y,u,i,o}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

shift + alt + {y,u,i,o}
    bspc node -z {left -50 0,bottom 0 50,top 0 -50,right 50 0}

# Contract window by moving one side inward
super + ctrl + shift + {y,u,i,o}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

alt + ctrl + shift + {y,u,i,o}
    bspc node -z {right -50 0,top 0 50,bottom 0 -50,left 50 0}

# Move floating window
super + {Left,Down,Up,Right}
    bspc node -v {-20 0,0 20,0 -20,20 0}

super + shift + {Left,Down,Up,Right}
    bspc node -v {-50 0,0 50,0 -50,50 0}

############################### Window Layouts ################################
# Alternate between tiled/monocle layout
super + m
    bspc desktop -l next

# Send newest marked node to newest preselected node
super + y
    bspc node newest.marked.local -n newest.!automatic.local

# Swap current node and biggest node
super + g
    bspc node -s biggest

# Set window state and node flags
super + {t,shift + t,shift + space,f}
    bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}
