#!/bin/sh
# Get ID of audio device by reading the
# outputted file containing the ID

bash ~/bin/audio_device_id.sh
id=$(cat ~/.config/devID)

if [ $id -eq 0 ]; then
		dev="Analog Stereo"
elif [ $id -eq 2 ]; then
		dev="JBL Flip 4"
else
		dev="Unknown (id=$id)"
fi

echo $dev
