# autogenerated by txs
#include:graphics
\ExplFileDate#S
\ExplLoaderFileDate#S
\ProvidesExplClass{arg1}{arg2}{arg3}{arg4}#S
\ProvidesExplFile{arg1}{arg2}{arg3}{arg4}#S
\ProvidesExplPackage{arg1}{arg2}{arg3}{arg4}#S
\color[opt]{arg1}#S
\color{arg1}#S
\expl#S
\l#S
