[Desktop Entry]
Name=DejaVu Sans Crux
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Crux
MetacityTheme=Mist
IconTheme=Crux
GtkColorScheme=fg_color:#000;bg_color:#d3d7cf;base_color:#fff;text_color:#000;selected_bg_color:#75507b;selected_fg_color:#fff;tooltip_bg_color:#F5F5B5;tooltip_fg_color:#000
CursorTheme=default
CursorSize=18
NotificationTheme=slider
BackgroundImage=/usr/share/backgrounds/scenery/argerich2.xml
