#! /bin/sh
#                  `                                  `
#              `,+ `                        `      ,`#
#             +#`,:``                       ``    '`@``+`
#           `; :# '  `                        `   `@``@,
#           #, `: ,      ``                      ``#`  : :
#           ;+ # ,               ++++++++++++++`   ; .+``+
#           ; #. '         `     @@@@@@@@@@@@@@`     ;#, #
#             #  :       `:'      @      ;. '@,      '.@
#          ,: #; ,        #`      @      ;` ;@+      .`@ +
#          . @,.+#       .@@     .#      ;` .@#    `'+` ;'
#          `@; ,+`       .@@   ` +:      ;`  @@     +:#,+;
#      `   #`#`# +       `@@    `@`@`    ;`  @@     ,`@,.;`
#          + ; +.,        #   `.,#,,#,```',` @@     @'` +.`
#         ``@'`,@`  `'@@@@@@@@@@@`+@#@@@@@+''@@     ,'; '#``
#          +`#;;,;  +@@,,,@@@@@@@.@+#@@#` .;`. `    @ +`;:.``
#         `' + # .  +@@`.`#@@@@@@:@##@+ #@@@@@#     @`: @.`  `
#           @'`+@.  +@@:,:#@@@@@@'@@#@ @@@@#@@@@`    #+`##    `
#          ' ;`,;+  +@@@@+@@@@@@@+@@@`#@@;   .@@#   @`',.,
#          ;`+ + :  +@#  `  :@@@@@#@# @@: :@+ `@@`  @`, +,
#           @'`##   ''`##@@@.,@@@@,:..@@ ;@+@@ +@#  `@#'#+
#            @++      @@@@@@@ #@@@@@:#@@ @' `@ :@@    ##;
#            .@'     `@@.  +@+`@@@@#;.@@ @@ ;@ '@+  ` @@
#             #`    `:@#.`#`@@       .@@` @@@, @@+   `+`
#             :,   ` :@@`'+.@@       `@@@  `` +#@     @
#              +    ``@@, `@@;         @@@+.;@#@:     @
#              @     `'@@@@@@          `@#@@@@@:     `+
#              '`      :@@@'             :#@#+```    #`
#               @      `                        `    @
#               ',      `                        `  @`
#
#                   ###### #### ###### #     # #######
#                    #   # #     #   # #  #  # #  #  #
#                   ###### #### ###### #  #  # #  #  #
#                    #   #    #  #     #  #  # #  #  #
#                   ###### ####  #     ####### #     #
#
########################## BSPWM Configuration File ###########################


################################## Main Setup ##################################
sxhkd &
setupBspwm

############################## Window Configuration ##############################
bspc config top_padding    8
bspc config bottom_padding 8
bspc config left_padding   8
bspc config right_padding  8

bspc config border_width 3
bspc config window_gap   10

bspc config split_ratio        0.5
bspc config borderless_monocle false
bspc config gapless_monocle    false

bspc config focus_follow_pointer true

############################ Workspace Management #############################
bspc monitor eDP1 -d S1 S2 S3 S4 S5
bspc monitor DP3  -d A1 A2 A3 A4 A5
ctrl
# Application rules
# Editors [monitor 08]
bspc rule -a Gimp     desktop='^9'
bspc rule -a Krita    desktop='^8'
bspc rule -a Inkscape desktop='^8'
bspc rule -a Fiji     desktop='^8' state=floating follow=on

# Social [monitor 09]
bspc rule -a Steam    desktop='^9'
bspc rule -a Messages desktop='^9'
bspc rule -a caprine  desktop='^9'
bspc rule -a yakyak   desktop='^9'
bspc rule -a Slack    desktop='^9'
bspc rule -a Discord  desktop='^9'

# Music [monitor 10]
bspc rule -a gpmdp   desktop='^10'
bspc rule -a spotify desktop='^10'

# Floating
bspc rule -a URxvt :htop       state=floating follow=on
bspc rule -a URxvt :gotop      state=floating follow=on
bspc rule -a URxvt :pulsemixer state=floating follow=on

############################## Bar Configuration ##############################
## TODO
# Polybar or better Lemonbar
# Applets [wifi | bluetooth | power options]
## Add default lemonbar panel for now
#panel &
polybar -c ~/.config/polybar/polybar.conf main -q --reload      &
polybar -c ~/.config/polybar/polybar.conf secondary -q --reload &

