#!/bin/bash

case $BLOCK_BUTTON in
	1) $TERMINAL -- alsamixer & disown ;;
esac

volume=$(amixer get Master | grep -E -o '[0-9][0-9]?%')
isMute=$(amixer get Master | grep -E -o "off")
printpastatus() { 
	[[ "$isMute" = "off" ]] && echo -n 🔇 && exit
    echo 🔊 $volume ;
}
printpastatus
