#!/bin/sh
# fluxbox startup-script:

# Change keymap:
xmodmap "/home/jbustamante/.Xmodmap"

# Set Xresources and wallpaper
feh --bg-scale $HOME/.config/wall.png
regencolors $WALEND 1

# Set displays
setScreens 0 nvidia home;

# Touchpad and mouse
touchpadctl tap
unclutter -idle 2 &
idesk &

# MPD | Compton | Conky | Dunst
mpd &
#myconky 1 &
dunst   -config ~/.config/dunst/dunstrc &
compton --config ~/.config/compton/compton.conf -b &

# URxvt daemon
urxvtd -q -o -f &

# Start fluxbox.
#exec fluxbox -log "/home/jbustamante/.fluxbox/log"

# Setup Xfce Panel.
xfce4-panel &
