# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Aliases for commands. The keys of the given dictionary are the
# aliases, while the values are the commands they map to.
# Type: Dict
c.aliases = {'q': 'quit', 'w': 'session-save', 'wq': 'quit --save'}

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Directory to save downloads to. If unset, a sensible OS-specific
# default is used.
# Type: Directory
c.downloads.location.directory = '~/Downloads'

######################## End of Default Config ################################
## Show a scrollbar.
c.scrolling.bar = 'never'
c.url.default_page = 'https://bing.com'
c.url.start_pages = ['https://bing.com']

## The default zoom level.
## Type: Perc
c.zoom.default = '100%'

## Definitions of search engines which can be used via the address bar.
## Maps a searchengine name (such as `DEFAULT`, or `ddg`) to a URL with a
## `{}` placeholder. The placeholder will be replaced by the search term,
## use `{{` and `}}` for literal `{`/`}` signs. The searchengine named
## `DEFAULT` is used when `url.auto_search` is turned on and something
## else than a URL was entered to be opened. Other search engines can be
## used by prepending the search engine name to the search term, e.g.
## `:open google qutebrowser`.
## Type: Dict
c.url.searchengines = {
      'DEFAULT': 'https://bing.com/?q={}',
      'b': 'https://bing.com/?q={}',
      'bim': 'https://www.bing.com/images/search?q={}',
      'g': 'https://www.google.com/search?q={}',
      'gim': 'https://www.google.com/search?tbm=isch&q={}',
      'd': 'https://duckduckgo.com/?q={}',
      'dim': 'https://duckduckgo.com/?q={}&iar=images&iax=images&ia=images',
      'aw': 'https://wiki.archlinux.org/index.php?title=Special%3ASearch&search={}',
      'wt': 'http://en.wiktionary.org/?search={}',
      'w': 'https://www.wikipedia.org/search-redirect.php?family=wikipedia&language=en&search={}&language=en&go=Go',
      'yt': 'https://www.youtube.com/results?search_query={}',
        }

## Behavior when the last tab is closed.
## Type: String
## Valid values:
##   - ignore: Don't do anything.
##   - blank: Load a blank page.
##   - startpage: Load the start page.
##   - default-page: Load the default page.
##   - close: Close the window.
c.tabs.last_close = 'close'

## Bindings for normal mode
config.bind('d', 'scroll-page 0 0.5')
config.bind('u', 'scroll-page 0 -0.5')
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('<Ctrl-,>', 'tab-give')

## Bindings for caret mode

## Bindings for command mode

## Bindings for hint mode

## Bindings for insert mode

## Bindings for passthrough mode

## Bindings for prompt mode

## Bindings for register mode

## Source custom shortcut bindings
config.source('shortcuts.py')

